import io
import csv
import logging
from flask import Blueprint, render_template, session, redirect, url_for, flash, request, make_response
from fpdf import FPDF
from app.controllers.report_controller import ReportController

report_bp = Blueprint('report_routes', __name__)
report_logic = ReportController()

@report_bp.route('/reports', methods=['GET'])
def reports_management() -> str:
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))
    
    view_data = report_logic.load_reports_history()
    role = session.get('role', 'Staff')
    return render_template('admin/reports.html', data=view_data, role=role)

@report_bp.route('/reports/generate', methods=['POST'])
def generate_report() -> str:
    r_type = request.form.get('report_type')
    start_date = request.form.get('start_date')
    end_date = request.form.get('end_date')
    user = session.get('username', 'Admin Alice')
    
    resp = report_logic.generate_new_report(r_type, start_date, end_date, user)
    flash(resp.get("message"), "success" if resp.get("success") else "danger")
    return redirect(url_for('report_routes.reports_management'))

@report_bp.route('/reports/download/<report_id>/<file_type>')
def download_report(report_id: str, file_type: str):
    """Generates and triggers a real file download."""
    report = report_logic.model.get_report_by_id(report_id)
    if not report:
        flash("Report not found.", "danger")
        return redirect(url_for('report_routes.reports_management'))

    filename = f"Report_{report_id}"

    # --- LOGICA PDF ---
    if file_type == 'pdf':
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(190, 10, txt="TRANSPORT COMPANY - OFFICIAL REPORT", ln=True, align='C')
        pdf.ln(10)
        
        # Tabel date
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(40, 10, "Field", border=1)
        pdf.cell(150, 10, "Details", border=1, ln=True)
        
        pdf.set_font("Arial", '', 12)
        data_rows = [
            ("Report ID", report['id']),
            ("Report Name", report['name']),
            ("Type", report['type']),
            ("Generated By", report['generated_by']),
            ("Date", report['generated_date'])
        ]
        
        for label, value in data_rows:
            pdf.cell(40, 10, label, border=1)
            pdf.cell(150, 10, str(value), border=1, ln=True)

        # Pregatim raspunsul pentru browser
        response = make_response(pdf.output(dest='S').encode('latin-1'))
        response.headers["Content-Disposition"] = f"attachment; filename={filename}.pdf"
        response.headers["Content-type"] = "application/pdf"
        return response

    # --- LOGICA CSV ---
    elif file_type == 'csv':
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['ID', 'Name', 'Type', 'Generated By', 'Date'])
        writer.writerow([report['id'], report['name'], report['type'], report['generated_by'], report['generated_date']])
        
        response = make_response(output.getvalue())
        response.headers["Content-Disposition"] = f"attachment; filename={filename}.csv"
        response.headers["Content-type"] = "text/csv"
        return response

    # --- LOGICA TXT ---
    elif file_type == 'txt':
        content = f"REPORT {report_id}\n" + "-"*20 + "\n"
        content += f"Name: {report['name']}\nType: {report['type']}\nUser: {report['generated_by']}\nDate: {report['generated_date']}"
        
        response = make_response(content)
        response.headers["Content-Disposition"] = f"attachment; filename={filename}.txt"
        response.headers["Content-type"] = "text/plain"
        return response

    return redirect(url_for('report_routes.reports_management'))