import sqlite3
import logging
from typing import Dict, List, Any

DB_PATH: str = "instance/database.sqlite"

class CustomerModel:
    """Handles direct database operations for the Customer Portal."""

    def get_customer_requests(self, username: str) -> List[Dict[str, Any]]:
        """Retrieves all transport requests belonging to the logged-in customer."""
        requests: List[Dict[str, Any]] = []
        try:
            with sqlite3.connect(DB_PATH) as connection:
                connection.row_factory = sqlite3.Row
                db_cursor = connection.cursor()
                
               
                
                db_cursor.execute(
                    """
                    SELECT id, cargo_type, weight, pickup, delivery, preferred_date, status, vehicle_type, 
                           COALESCE(price_offer, estimated_price) AS price_offer 
                    FROM transport_requests 
                    WHERE client = ? ORDER BY id DESC
                    """, 
                    (username,)
                )
                
                rows = db_cursor.fetchall()
                for row in rows:
                    requests.append(dict(row))
                return requests
        except sqlite3.Error as db_error:
            logging.error(f"Error retrieving customer requests: {db_error}")
            return requests

    def insert_customer_request(self, r_id: str, client: str, c_type: str, desc: str, weight: float, volume: float, pickup: str, delivery: str, date: str, status: str, v_type: str, price: float) -> bool:
        """Safely inserts a new request generated by the customer."""
        try:
            with sqlite3.connect(DB_PATH) as connection:
                db_cursor = connection.cursor()
               
                db_cursor.execute(
                    "INSERT INTO transport_requests (id, client, cargo_type, description, weight, volume, pickup, delivery, preferred_date, status, vehicle_type, estimated_price) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (r_id, client, c_type, desc, weight, volume, pickup, delivery, date, status, v_type, price)
                )
                connection.commit()
                return True
        except sqlite3.Error as e:
            logging.error(f"Insert request error: {e}")
            return False

    def update_request_status(self, request_id: str, new_status: str, customer_name: str) -> bool:
        """Updates the status (Accept/Reject/Negotiate) verifying ownership."""
        try:
            with sqlite3.connect(DB_PATH) as connection:
                db_cursor = connection.cursor()
                
                if new_status == 'Accepted':
                   
                   
                    db_cursor.execute(
                        """
                        UPDATE transport_requests 
                        SET status = ?, 
                            price_offer = COALESCE(price_offer, estimated_price) 
                        WHERE id = ? AND client = ?
                        """,
                        (new_status, request_id, customer_name)
                    )
                else:
                
                    db_cursor.execute(
                        "UPDATE transport_requests SET status = ? WHERE id = ? AND client = ?",
                        (new_status, request_id, customer_name)
                    )
                    
                connection.commit()
                return True
        except sqlite3.Error as db_error:
            logging.error(f"Error updating request status: {db_error}")
            return False